import type { LandingModel } from '../../brand-analysis/types';
import { escapeHtml } from '../../../utils/sanitize';
import { renderReviewCards } from './reviews';

/** Legal: trust-first with spotlight image and subtle procedural effects. */
export function renderLegal(m: LandingModel): string {
  const H = escapeHtml;
  const sideImg = 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=1400&auto=format&fit=crop&q=80';
  const D = { bg:'#09090B', surface:'#111113', card:'#18181B', border:'rgba(255,255,255,0.07)', text:'#EFEFEF', muted:'rgba(255,255,255,0.42)', primary:m.palette.primary, accent:m.palette.accent };
  const areas = m.features.map(f => `<div style="padding:26px 22px;background:${D.card};border-top:2px solid ${D.primary};"><p style="color:${D.text};font-size:15px;line-height:1.7;margin:0;">${H(f)}</p></div>`).join('');
  return `
  <style>
    @keyframes underlineDraw { from { width:0; } to { width:100%; } }
    @keyframes legalFadeIn { from { opacity:0; transform:translateY(18px); } to { opacity:1; transform:translateY(0); } }
    @keyframes legalPulse { 0%,100% { opacity:0.18; } 50% { opacity:0.34; } }
    .legal-underline { position:relative; display:inline; }
    .legal-underline::after { content:''; position:absolute; bottom:-5px; left:0; height:2px; background:${D.accent}; animation:underlineDraw 1.1s ease 0.6s both; width:0; }
    .legal-hero, .legal-hero-img { animation: legalFadeIn 0.7s ease both; }
    .legal-hero-img { animation-delay:0.2s; }
    .legal-grid::before { content:''; position:absolute; inset:0; background-image:linear-gradient(rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.04) 1px, transparent 1px); background-size:32px 32px; opacity:0.35; }
    .legal-glow { animation: legalPulse 4s ease-in-out infinite; }
  </style>
  <section style="background:${D.bg};font-family:${m.font};color:${D.text};min-height:100vh;">
    <div style="background:${D.surface};padding:10px 60px;border-bottom:1px solid ${D.border};"><div style="max-width:1200px;margin:0 auto;display:flex;justify-content:flex-end;gap:20px;"><a style="color:${D.muted};text-decoration:none;font-size:12px;letter-spacing:0.04em;">聯絡我們</a><span style="color:${D.border};">|</span><a style="color:${D.muted};text-decoration:none;font-size:12px;letter-spacing:0.04em;">中文</a></div></div>
    <nav style="background:${D.surface};border-bottom:1px solid ${D.border};padding:0 60px;"><div style="max-width:1200px;margin:0 auto;height:68px;display:flex;align-items:center;justify-content:space-between;"><div><span style="font-size:19px;font-weight:700;color:${D.text};">${H(m.brandName)}</span><span style="font-size:11px;color:${D.muted};margin-left:10px;letter-spacing:0.08em;text-transform:uppercase;">法律顧問</span></div><div style="display:flex;gap:36px;align-items:center;"><a style="color:${D.muted};text-decoration:none;font-size:13px;">服務領域</a><a style="color:${D.muted};text-decoration:none;font-size:13px;">顧問團隊</a><a style="color:${D.muted};text-decoration:none;font-size:13px;">觀點洞察</a><button style="background:${D.primary};color:#fff;border:none;padding:11px 22px;font-size:13px;cursor:pointer;font-weight:600;">${H(m.cta)}</button></div></div></nav>
    <div style="max-width:1200px;margin:0 auto;padding:100px 60px;display:grid;grid-template-columns:3fr 2fr;gap:80px;align-items:center;"><div class="legal-hero"><div style="display:flex;align-items:center;gap:10px;margin-bottom:28px;"><div style="width:28px;height:1px;background:${D.accent};"></div><span style="font-size:11px;color:${D.muted};letter-spacing:0.14em;text-transform:uppercase;">Cross-border counsel / dispute strategy / commercial protection</span></div><h1 style="font-size:clamp(28px,3.5vw,48px);font-weight:700;color:${D.text};margin:0 0 18px;line-height:1.2;"><span class="legal-underline">${H(m.brandName)}</span><span style="display:block;font-weight:400;font-size:0.78em;margin-top:10px;color:${D.muted};">${H(m.tagline)}</span></h1><p style="font-size:17px;color:${D.muted};line-height:1.8;margin:0 0 40px;">${H(m.subheadline)}</p><div style="display:flex;gap:16px;align-items:center;"><button style="background:${D.primary};color:#fff;border:none;padding:14px 32px;font-size:15px;font-weight:600;cursor:pointer;">${H(m.cta)}</button><a style="font-size:13px;color:${D.muted};text-decoration:underline;cursor:pointer;">Schedule a review</a></div></div><div class="legal-hero-img legal-grid" style="position:relative;background:${D.card};padding:26px;border:1px solid ${D.border};overflow:hidden;"><div class="legal-glow" style="position:absolute;inset:auto -80px -120px auto;width:240px;height:240px;border-radius:50%;background:${D.primary};filter:blur(90px);"></div><img src="${sideImg}" alt="legal advisory" style="position:relative;z-index:1;width:100%;height:320px;object-fit:cover;margin-bottom:20px;filter:brightness(0.72);" /><div style="position:relative;z-index:1;display:grid;grid-template-columns:1fr 1fr;gap:12px;text-align:center;">${[['20+','Years'],['500+','Matters'],['98%','Retention']].map(([v,l])=>`<div style="padding:16px;background:${D.surface};border:1px solid ${D.border};"><div style="font-size:22px;font-weight:700;color:${D.primary};">${v}</div><div style="font-size:11px;color:${D.muted};margin-top:4px;letter-spacing:0.04em;">${l}</div></div>`).join('')}</div></div></div>
    <div style="background:${D.primary};padding:72px 60px;"><div style="max-width:1200px;margin:0 auto;"><h2 style="font-size:30px;font-weight:700;margin:0 0 18px;color:#fff;">${H(m.pain)}</h2><p style="font-size:17px;line-height:1.85;color:rgba(255,255,255,0.8);max-width:820px;">${H(m.solution)}</p></div></div>
    <div style="max-width:1200px;margin:0 auto;padding:80px 60px;display:grid;grid-template-columns:2fr 1fr;gap:40px;align-items:start;"><div><h2 style="font-size:26px;font-weight:700;margin:0 0 10px;color:${D.text};">服務領域</h2><div style="height:2px;width:44px;background:${D.accent};margin-bottom:36px;"></div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:14px;">${areas}</div></div><img src="https://images.unsplash.com/photo-1453945619913-79ec89a82c51?w=1200&auto=format&fit=crop&q=80" alt="legal team" style="width:100%;height:360px;object-fit:cover;border:1px solid ${D.border};filter:brightness(0.76);" /></div>
    <div style="background:${D.surface};padding:72px 60px;border-top:1px solid ${D.border};"><div style="max-width:1200px;margin:0 auto;"><h2 style="font-size:26px;font-weight:700;margin:0 0 10px;color:${D.text};">客戶回饋</h2><div style="height:2px;width:44px;background:${D.accent};margin-bottom:36px;"></div>${renderReviewCards(m, { theme: 'legal', columns: 2 })}</div></div>
    <div style="text-align:center;padding:80px 40px;border-top:3px solid ${D.primary};"><p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:${D.muted};margin:0 0 12px;">${H(m.brandName)}</p><h2 style="font-size:34px;font-weight:700;color:${D.text};margin:0 0 12px;">${H(m.tagline)}</h2><p style="font-size:15px;color:${D.muted};margin:0 0 32px;">Confident advice for material decisions.</p><button style="background:${D.primary};color:#fff;border:none;padding:16px 48px;font-size:16px;font-weight:700;cursor:pointer;">${H(m.cta)}</button></div>
  </section>`;
}


